<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TeamsSeeder extends Seeder
{
    
    public function run()
    {
        DB::table('teams')->insert([
                [
                    'name' => 'Rajesh Jain',
                    'designation' => 'Practicing Advocate, Rajasthan High Court',
                    'area_of_practice' => json_encode(['Civil Law', 'Constitutional Law']),
                    'adr_services' => json_encode(['Mediation', 'Legal Consultation']),
                    'all_rounder' => true,
                    'type' => 'Advocate',
                    'email' => 'rajeshjain@example.com',
                    'phone' => '9811111111',
                    'experience' => json_encode(['12 years in Rajasthan High Court']),
                    'education' => json_encode(['LLB - University of Rajasthan']),
                    'awards' => json_encode(['Excellence in Legal Services 2018']),
                    'socials' => json_encode(['linkedin' => 'https://linkedin.com/in/rajeshjain']),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'profile_image' => 'assets/img/my/profile_icon2.png'
                    
                ],
                [
                    'name' => 'Ramesh Chand Sharma',
                    'designation' => 'Retired District & Sessions Judge, Rajasthan',
                    'area_of_practice' => json_encode(['Criminal Law', 'Judicial Services']),
                    'adr_services' => json_encode(['Arbitration']),
                    'all_rounder' => false,
                    'type' => 'Retired Judge',
                    'email' => 'rameshsharma@example.com',
                    'phone' => '9822222222',
                    'experience' => json_encode(['35 years in Rajasthan Judiciary']),
                    'education' => json_encode(['LLB - Delhi University']),
                    'awards' => json_encode(['Lifetime Judicial Excellence Award']),
                    'socials' => json_encode(['linkedin' => 'https://linkedin.com/in/rameshsharma']),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'profile_image' => 'assets/img/my/profile_icon2.png'
                ],
                [
                    'name' => 'Ashok Sharma',
                    'designation' => 'Retired District & Sessions Judge, Rajasthan',
                    'area_of_practice' => json_encode(['Civil Law', 'Family Law']),
                    'adr_services' => json_encode(['Arbitration']),
                    'all_rounder' => false,
                    'type' => 'Retired Judge',
                    'email' => 'ashoksharma@example.com',
                    'phone' => '9833333333',
                    'experience' => json_encode(['30 years in Rajasthan Judiciary']),
                    'education' => json_encode(['LLB - Banaras Hindu University']),
                    'awards' => json_encode(['Distinguished Judge Award']),
                    'socials' => json_encode(['linkedin' => 'https://linkedin.com/in/ashoksharma']),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'profile_image' => 'assets/img/my/profile_icon2.png'
                ],
                [
                    'name' => 'Jai Prakash Sharma',
                    'designation' => 'Practicing Advocate, CMM Court, Rajasthan',
                    'area_of_practice' => json_encode(['Criminal Law']),
                    'adr_services' => json_encode(['Legal Aid']),
                    'all_rounder' => true,
                    'type' => 'Advocate',
                    'email' => 'jaiprakash@example.com',
                    'phone' => '9844444444',
                    'experience' => json_encode(['15 years in CMM Court']),
                    'education' => json_encode(['LLB - Rajasthan University']),
                    'awards' => json_encode(['Top Defense Advocate 2021']),
                    'socials' => json_encode(['linkedin' => 'https://linkedin.com/in/jaisharma']),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'profile_image' => 'assets/img/my/profile_icon2.png'
                ],
                [
                    'name' => 'Naveen Sharma',
                    'designation' => 'Practicing Advocate, CMM Court',
                    'area_of_practice' => json_encode(['Civil Law', 'Property Law']),
                    'adr_services' => json_encode(['Mediation']),
                    'all_rounder' => false,
                    'type' => 'Advocate',
                    'email' => 'naveen.sharma@example.com',
                    'phone' => '9855555555',
                    'experience' => json_encode(['10 years in CMM Court']),
                    'education' => json_encode(['LLB - MLSU, Udaipur']),
                    'awards' => json_encode(['Client Choice Award']),
                    'socials' => json_encode(['linkedin' => 'https://linkedin.com/in/naveensharma']),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'profile_image' => 'assets/img/my/profile_icon2.png'
                ],
                [
                    'name' => 'K.R. Sharma',
                    'designation' => 'Retired Chief Judicial Magistrate',
                    'area_of_practice' => json_encode(['Judicial Services', 'Criminal Law']),
                    'adr_services' => json_encode(['Legal Advisory']),
                    'all_rounder' => false,
                    'type' => 'Retired Judge',
                    'email' => 'krsharma@example.com',
                    'phone' => '9866666666',
                    'experience' => json_encode(['32 years in Rajasthan Judicial Services']),
                    'education' => json_encode(['LLB - Jodhpur University']),
                    'awards' => json_encode(['Judiciary Service Medal']),
                    'socials' => json_encode(['linkedin' => 'https://linkedin.com/in/krsharma']),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'profile_image' => 'assets/img/my/profile_icon2.png'
                ],
                [
                    'name' => 'Arun Singh Shekhawat',
                    'designation' => 'Practicing Advocate, Rajasthan High Court',
                    'area_of_practice' => json_encode(['Corporate Law', 'Constitutional Law']),
                    'adr_services' => json_encode(['Arbitration', 'Mediation']),
                    'all_rounder' => true,
                    'type' => 'Advocate',
                    'email' => 'arunsingh@example.com',
                    'phone' => '9877777777',
                    'experience' => json_encode(['14 years in Rajasthan High Court']),
                    'education' => json_encode(['LLB - Symbiosis Law School']),
                    'awards' => json_encode(['Corporate Law Expert 2022']),
                    'socials' => json_encode(['linkedin' => 'https://linkedin.com/in/arunsingh']),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'profile_image' => 'assets/img/my/profile_icon2.png'
                ],
                [
                    'name' => 'Hemant Ruthala',
                    'designation' => 'Practicing Advocate, Rajasthan High Court',
                    'area_of_practice' => json_encode(['Criminal Law', 'Tax Law']),
                    'adr_services' => json_encode(['Legal Advice']),
                    'all_rounder' => true,
                    'type' => 'Advocate',
                    'email' => 'hemant.ruthala@example.com',
                    'phone' => '9888888888',
                    'experience' => json_encode(['9 years in Rajasthan High Court']),
                    'education' => json_encode(['LLB - National Law University, Jodhpur']),
                    'awards' => json_encode(['Young Lawyer of the Year 2023']),
                    'socials' => json_encode(['linkedin' => 'https://linkedin.com/in/hemant']),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'profile_image' => 'assets/img/my/profile_icon2.png'
                ],
                [
                    'name' => 'Mrs. Manju Singh Chundawat',
                    'designation' => 'Practicing Advocate, Rajasthan High Court',
                    'area_of_practice' => json_encode(['Family Law', 'Women Rights']),
                    'adr_services' => json_encode(['Mediation', 'Counseling']),
                    'all_rounder' => true,
                    'type' => 'Advocate',
                    'email' => 'manju.chundawat@example.com',
                    'phone' => '9899999999',
                    'experience' => json_encode(['11 years in Rajasthan High Court']),
                    'education' => json_encode(['LLB - Rajasthan University']),
                    'awards' => json_encode(['Women in Law Award']),
                    'socials' => json_encode(['linkedin' => 'https://linkedin.com/in/manjusingh']),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'profile_image' => 'assets/img/my/profile_icon2.png'
                ],
            
            [
                'name' => 'John Doe',
                'designation' => 'Senior Advocate',
                'area_of_practice' => json_encode(['Civil Law', 'Corporate Law']),
                'adr_services' => json_encode(['Arbitration', 'Mediation']),
                'all_rounder' => true,
                'type' => 'Advocate',
                'email' => 'johndoe@example.com',
                'phone' => '9876543210',
                'experience' => json_encode(['10 years in High Court', '5 years in Supreme Court']),
                'education' => json_encode(['LLB - Harvard University', 'LLM - Oxford University']),
                'awards' => json_encode(['Best Lawyer 2020', 'Top Arbitrator 2022']),
                'socials' => json_encode(['linkedin' => 'https://linkedin.com/in/johndoe', 'twitter' => 'https://twitter.com/johndoe']),
                'created_at' => now(),
                'updated_at' => now(),
                'profile_image' => 'assets/img/my/profile_icon2.png'
            ],
            [
                'name' => 'Jane Smith',
                'designation' => 'Corporate Lawyer',
                'area_of_practice' => json_encode(['Corporate Law', 'Tax Law']),
                'adr_services' => json_encode(['Negotiation', 'Mediation']),
                'all_rounder' => false,
                'type' => 'Lawyer',
                'email' => 'janesmith@example.com',
                'phone' => '9876543211',
                'experience' => json_encode(['7 years in Corporate Law', '3 years as Legal Advisor']),
                'education' => json_encode(['LLB - Yale University']),
                'awards' => json_encode(['Corporate Lawyer of the Year 2021']),
                'socials' => json_encode(['linkedin' => 'https://linkedin.com/in/janesmith']),
                'created_at' => now(),
                'updated_at' => now(),
                'profile_image' => 'assets/img/my/profile_icon2.png'
            ],
            [
                'name' => 'Robert Brown',
                'designation' => 'Retired Judge',
                'area_of_practice' => json_encode(['Criminal Law', 'Family Law']),
                'adr_services' => json_encode(['Arbitration', 'Conciliation']),
                'all_rounder' => true,
                'type' => 'Retired Judge',
                'email' => 'robertbrown@example.com',
                'phone' => '9876543212',
                'experience' => json_encode(['20 years as District Judge', '5 years as High Court Judge']),
                'education' => json_encode(['LLB - Cambridge University']),
                'awards' => json_encode(['Excellence in Justice Award 2019']),
                'socials' => json_encode(['linkedin' => 'https://linkedin.com/in/robertbrown']),
                'created_at' => now(),
                'updated_at' => now(),
                'profile_image' => 'assets/img/my/profile_icon2.png'
            ],
            [
                    'name' => 'RAJAN SHARMA',
                    'designation' => 'Director',
                    'area_of_practice' => null,
                    'adr_services' => null,
                    'all_rounder' => false,
                    'type' => 'Specialization 1', 
                    'email' => null,
                    'phone' => null,
                    'experience' => null,
                    'education' => null,
                    'awards' => null,
                    'socials' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                'profile_image' => 'assets/img/my/profile_icon2.png'
                ],
                [
                    'name' => 'SEEMA SHARMA',
                    'designation' => 'Director',
                    'area_of_practice' => null,
                    'adr_services' => null,
                    'all_rounder' => false,
                    'type' => 'Specialization 2',
                    'email' => null,
                    'phone' => null,
                    'experience' => null,
                    'education' => null,
                    'awards' => null,
                    'socials' => null,
                    'created_at' => now(),
                    'updated_at' => now(),
                'profile_image' => 'assets/img/my/profile_icon2.png'
                ]
    ]);
    }
}
